server:
  port: 8080

spring:


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  ses:
    sender-email: ${AWS_SES_SENDER_EMAIL}
  dynamodb:
    appointments-table: ${AWS_DYNAMODB_APPOINTMENTS_TABLE}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000